### ISSUE TITLE
WARNING in ./~/@angular/core/@angular/core.es5.js

### ISSUE THREAD

**Issue by stevermeister** [gonzofish/angular-library-set#33] opened 2017-05-03 13:39 UTC
when I'm doing 
`npm start`
getting 

```
WARNING in ./~/@angular/core/@angular/core.es5.js
5870:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
5886:15 Critical dependency: the request of a dependency is an expression
```

**Comment by gonzofish** [comment] 2017-05-03 14:19
I just ran into this the other day, let me see what I did to alleviate it

**Comment by gonzofish** [comment] 2017-05-03 14:25
The issue is that from Angular 2 -> Angular 4 there were some file structure changes. One of the changes was the location of the linker. I'll fix this in the project, but here's what you can do to fix it in the meantime:

In the `webpack/webpack.*.js` files, change the first entry of the `ContextReplacementPlugin`:

```javascript
/angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
```

to

```javascript
/angular(\\|\/)core(\\|\/)((esm(\\|\/)src|src)(\\|\/)linker|@angular)/,
```

I'm fairly sure we can get rid of the `core/esm` stuff, but I'm going with a "rather safe than sorry" approach here.

**Comment by gonzofish** [comment] 2017-05-04 22:42
Closed by commit ed141

**Closed by gonzofish** 2017-05-04 22:42 UTC
